name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ChristianLempa/boilerplates

    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          owner: llvm
          base: main
          head: main
